### ISSUE TITLE
Megaphone --> Face

### ISSUE THREAD

**Issue by AtomSea** [embiimob/Sup#26]
When clicking the from face inside the megaphone option, and then selecting my profile, it will then give me a address that is not my profile

**Comment by embiimob** [comment]
i will need to research this more during our next working session...i thought perhaps i knew what was causing this...but the code checks out.  i have cleaned up the function a bit...

**Comment by embiimob** [comment]
disco tab was not being passed the testnet boolean.... this adversely effected the from selector
