### ISSUE TITLE
black then flash

### ISSUE THREAD

**Issue by AtomSea** [embiimob/Sup#8]
yeah beta! very excited! git that disco ball!

downloaded new version and using synced bitcoin testnet.
typed #flowersofwar and nothing shows.
however, when the scroll bar is clicked and moved, it will show a flash of an image, but then goes black again

**Comment by embiimob** [comment]
unable to re-produce... pending... 

the flash is expected behavior you are seeing the sup loading screen show momentarily before it returns nothing.

**Comment by embiimob** [comment]
cannot reproduce

**Comment by embiimob** [comment]
cannot reproduce

**Comment by embiimob** [comment]
cannot reproduce
